# Generated by Django 2.2.5 on 2020-07-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_webapp_draw', '0002_adjactive_adverb_verb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adjactive',
            new_name='adjective',
        ),
    ]
