# Generated by Django 2.2.5 on 2020-08-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webapp_draw', '0003_auto_20200724_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_images',
            name='desc',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='user_images',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
