# Generated by Django 2.2.5 on 2020-08-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_webapp_draw', '0007_auto_20200810_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_images',
            name='user',
        ),
    ]
