# Generated by Django 2.2.5 on 2020-08-10 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_webapp_draw', '0008_remove_user_images_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_images',
            name='up_date',
        ),
        migrations.AddField(
            model_name='user_images',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
