# Generated by Django 2.2.5 on 2020-08-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_webapp_draw', '0009_auto_20200810_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_images',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='user_images',
            name='title',
        ),
        migrations.RemoveField(
            model_name='user_images',
            name='user',
        ),
    ]
