# Generated by Django 2.2.5 on 2020-08-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webapp_draw', '0011_auto_20200810_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_images',
            name='image',
            field=models.ImageField(null=True, upload_to='user_images'),
        ),
    ]
