# Generated by Django 2.2.5 on 2020-08-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webapp_draw', '0015_auto_20200812_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_images',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='user_images'),
            preserve_default=False,
        ),
    ]
