# Generated by Django 2.2.5 on 2020-08-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webapp_draw', '0020_auto_20200812_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_images',
            name='desc',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
