# Generated by Django 2.2.5 on 2020-08-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webapp_draw', '0021_auto_20200813_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_images',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
