# Generated by Django 2.2.5 on 2020-08-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webapp_draw', '0022_auto_20200813_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_images',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='user_images'),
        ),
    ]
